// Code generated by ent, DO NOT EDIT.

package ent

import (
	"BazarMessenger/ent/predicate"
	"BazarMessenger/ent/profileandsetting"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileAndSettingQuery is the builder for querying ProfileAndSetting entities.
type ProfileAndSettingQuery struct {
	config
	ctx        *QueryContext
	order      []profileandsetting.OrderOption
	inters     []Interceptor
	predicates []predicate.ProfileAndSetting
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProfileAndSettingQuery builder.
func (pasq *ProfileAndSettingQuery) Where(ps ...predicate.ProfileAndSetting) *ProfileAndSettingQuery {
	pasq.predicates = append(pasq.predicates, ps...)
	return pasq
}

// Limit the number of records to be returned by this query.
func (pasq *ProfileAndSettingQuery) Limit(limit int) *ProfileAndSettingQuery {
	pasq.ctx.Limit = &limit
	return pasq
}

// Offset to start from.
func (pasq *ProfileAndSettingQuery) Offset(offset int) *ProfileAndSettingQuery {
	pasq.ctx.Offset = &offset
	return pasq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pasq *ProfileAndSettingQuery) Unique(unique bool) *ProfileAndSettingQuery {
	pasq.ctx.Unique = &unique
	return pasq
}

// Order specifies how the records should be ordered.
func (pasq *ProfileAndSettingQuery) Order(o ...profileandsetting.OrderOption) *ProfileAndSettingQuery {
	pasq.order = append(pasq.order, o...)
	return pasq
}

// First returns the first ProfileAndSetting entity from the query.
// Returns a *NotFoundError when no ProfileAndSetting was found.
func (pasq *ProfileAndSettingQuery) First(ctx context.Context) (*ProfileAndSetting, error) {
	nodes, err := pasq.Limit(1).All(setContextOp(ctx, pasq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{profileandsetting.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) FirstX(ctx context.Context) *ProfileAndSetting {
	node, err := pasq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProfileAndSetting ID from the query.
// Returns a *NotFoundError when no ProfileAndSetting ID was found.
func (pasq *ProfileAndSettingQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pasq.Limit(1).IDs(setContextOp(ctx, pasq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{profileandsetting.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) FirstIDX(ctx context.Context) int {
	id, err := pasq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProfileAndSetting entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProfileAndSetting entity is found.
// Returns a *NotFoundError when no ProfileAndSetting entities are found.
func (pasq *ProfileAndSettingQuery) Only(ctx context.Context) (*ProfileAndSetting, error) {
	nodes, err := pasq.Limit(2).All(setContextOp(ctx, pasq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{profileandsetting.Label}
	default:
		return nil, &NotSingularError{profileandsetting.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) OnlyX(ctx context.Context) *ProfileAndSetting {
	node, err := pasq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProfileAndSetting ID in the query.
// Returns a *NotSingularError when more than one ProfileAndSetting ID is found.
// Returns a *NotFoundError when no entities are found.
func (pasq *ProfileAndSettingQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pasq.Limit(2).IDs(setContextOp(ctx, pasq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{profileandsetting.Label}
	default:
		err = &NotSingularError{profileandsetting.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) OnlyIDX(ctx context.Context) int {
	id, err := pasq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProfileAndSettings.
func (pasq *ProfileAndSettingQuery) All(ctx context.Context) ([]*ProfileAndSetting, error) {
	ctx = setContextOp(ctx, pasq.ctx, "All")
	if err := pasq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProfileAndSetting, *ProfileAndSettingQuery]()
	return withInterceptors[[]*ProfileAndSetting](ctx, pasq, qr, pasq.inters)
}

// AllX is like All, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) AllX(ctx context.Context) []*ProfileAndSetting {
	nodes, err := pasq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProfileAndSetting IDs.
func (pasq *ProfileAndSettingQuery) IDs(ctx context.Context) (ids []int, err error) {
	if pasq.ctx.Unique == nil && pasq.path != nil {
		pasq.Unique(true)
	}
	ctx = setContextOp(ctx, pasq.ctx, "IDs")
	if err = pasq.Select(profileandsetting.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) IDsX(ctx context.Context) []int {
	ids, err := pasq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pasq *ProfileAndSettingQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, pasq.ctx, "Count")
	if err := pasq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, pasq, querierCount[*ProfileAndSettingQuery](), pasq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) CountX(ctx context.Context) int {
	count, err := pasq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pasq *ProfileAndSettingQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, pasq.ctx, "Exist")
	switch _, err := pasq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (pasq *ProfileAndSettingQuery) ExistX(ctx context.Context) bool {
	exist, err := pasq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProfileAndSettingQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pasq *ProfileAndSettingQuery) Clone() *ProfileAndSettingQuery {
	if pasq == nil {
		return nil
	}
	return &ProfileAndSettingQuery{
		config:     pasq.config,
		ctx:        pasq.ctx.Clone(),
		order:      append([]profileandsetting.OrderOption{}, pasq.order...),
		inters:     append([]Interceptor{}, pasq.inters...),
		predicates: append([]predicate.ProfileAndSetting{}, pasq.predicates...),
		// clone intermediate query.
		sql:  pasq.sql.Clone(),
		path: pasq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (pasq *ProfileAndSettingQuery) GroupBy(field string, fields ...string) *ProfileAndSettingGroupBy {
	pasq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProfileAndSettingGroupBy{build: pasq}
	grbuild.flds = &pasq.ctx.Fields
	grbuild.label = profileandsetting.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (pasq *ProfileAndSettingQuery) Select(fields ...string) *ProfileAndSettingSelect {
	pasq.ctx.Fields = append(pasq.ctx.Fields, fields...)
	sbuild := &ProfileAndSettingSelect{ProfileAndSettingQuery: pasq}
	sbuild.label = profileandsetting.Label
	sbuild.flds, sbuild.scan = &pasq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProfileAndSettingSelect configured with the given aggregations.
func (pasq *ProfileAndSettingQuery) Aggregate(fns ...AggregateFunc) *ProfileAndSettingSelect {
	return pasq.Select().Aggregate(fns...)
}

func (pasq *ProfileAndSettingQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range pasq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, pasq); err != nil {
				return err
			}
		}
	}
	for _, f := range pasq.ctx.Fields {
		if !profileandsetting.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pasq.path != nil {
		prev, err := pasq.path(ctx)
		if err != nil {
			return err
		}
		pasq.sql = prev
	}
	return nil
}

func (pasq *ProfileAndSettingQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProfileAndSetting, error) {
	var (
		nodes = []*ProfileAndSetting{}
		_spec = pasq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProfileAndSetting).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProfileAndSetting{config: pasq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pasq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (pasq *ProfileAndSettingQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pasq.querySpec()
	_spec.Node.Columns = pasq.ctx.Fields
	if len(pasq.ctx.Fields) > 0 {
		_spec.Unique = pasq.ctx.Unique != nil && *pasq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, pasq.driver, _spec)
}

func (pasq *ProfileAndSettingQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(profileandsetting.Table, profileandsetting.Columns, sqlgraph.NewFieldSpec(profileandsetting.FieldID, field.TypeInt))
	_spec.From = pasq.sql
	if unique := pasq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if pasq.path != nil {
		_spec.Unique = true
	}
	if fields := pasq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileandsetting.FieldID)
		for i := range fields {
			if fields[i] != profileandsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pasq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pasq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pasq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pasq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pasq *ProfileAndSettingQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pasq.driver.Dialect())
	t1 := builder.Table(profileandsetting.Table)
	columns := pasq.ctx.Fields
	if len(columns) == 0 {
		columns = profileandsetting.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pasq.sql != nil {
		selector = pasq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pasq.ctx.Unique != nil && *pasq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range pasq.predicates {
		p(selector)
	}
	for _, p := range pasq.order {
		p(selector)
	}
	if offset := pasq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pasq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ProfileAndSettingGroupBy is the group-by builder for ProfileAndSetting entities.
type ProfileAndSettingGroupBy struct {
	selector
	build *ProfileAndSettingQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pasgb *ProfileAndSettingGroupBy) Aggregate(fns ...AggregateFunc) *ProfileAndSettingGroupBy {
	pasgb.fns = append(pasgb.fns, fns...)
	return pasgb
}

// Scan applies the selector query and scans the result into the given value.
func (pasgb *ProfileAndSettingGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pasgb.build.ctx, "GroupBy")
	if err := pasgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfileAndSettingQuery, *ProfileAndSettingGroupBy](ctx, pasgb.build, pasgb, pasgb.build.inters, v)
}

func (pasgb *ProfileAndSettingGroupBy) sqlScan(ctx context.Context, root *ProfileAndSettingQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pasgb.fns))
	for _, fn := range pasgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pasgb.flds)+len(pasgb.fns))
		for _, f := range *pasgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pasgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pasgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProfileAndSettingSelect is the builder for selecting fields of ProfileAndSetting entities.
type ProfileAndSettingSelect struct {
	*ProfileAndSettingQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pass *ProfileAndSettingSelect) Aggregate(fns ...AggregateFunc) *ProfileAndSettingSelect {
	pass.fns = append(pass.fns, fns...)
	return pass
}

// Scan applies the selector query and scans the result into the given value.
func (pass *ProfileAndSettingSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pass.ctx, "Select")
	if err := pass.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProfileAndSettingQuery, *ProfileAndSettingSelect](ctx, pass.ProfileAndSettingQuery, pass, pass.inters, v)
}

func (pass *ProfileAndSettingSelect) sqlScan(ctx context.Context, root *ProfileAndSettingQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pass.fns))
	for _, fn := range pass.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pass.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pass.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
