// Code generated by ent, DO NOT EDIT.

package ent

import (
	"BazarMessenger/ent/predicate"
	"BazarMessenger/ent/profileandsetting"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileAndSettingUpdate is the builder for updating ProfileAndSetting entities.
type ProfileAndSettingUpdate struct {
	config
	hooks    []Hook
	mutation *ProfileAndSettingMutation
}

// Where appends a list predicates to the ProfileAndSettingUpdate builder.
func (pasu *ProfileAndSettingUpdate) Where(ps ...predicate.ProfileAndSetting) *ProfileAndSettingUpdate {
	pasu.mutation.Where(ps...)
	return pasu
}

// Mutation returns the ProfileAndSettingMutation object of the builder.
func (pasu *ProfileAndSettingUpdate) Mutation() *ProfileAndSettingMutation {
	return pasu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pasu *ProfileAndSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pasu.sqlSave, pasu.mutation, pasu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pasu *ProfileAndSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := pasu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pasu *ProfileAndSettingUpdate) Exec(ctx context.Context) error {
	_, err := pasu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pasu *ProfileAndSettingUpdate) ExecX(ctx context.Context) {
	if err := pasu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pasu *ProfileAndSettingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(profileandsetting.Table, profileandsetting.Columns, sqlgraph.NewFieldSpec(profileandsetting.FieldID, field.TypeInt))
	if ps := pasu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pasu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileandsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pasu.mutation.done = true
	return n, nil
}

// ProfileAndSettingUpdateOne is the builder for updating a single ProfileAndSetting entity.
type ProfileAndSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProfileAndSettingMutation
}

// Mutation returns the ProfileAndSettingMutation object of the builder.
func (pasuo *ProfileAndSettingUpdateOne) Mutation() *ProfileAndSettingMutation {
	return pasuo.mutation
}

// Where appends a list predicates to the ProfileAndSettingUpdate builder.
func (pasuo *ProfileAndSettingUpdateOne) Where(ps ...predicate.ProfileAndSetting) *ProfileAndSettingUpdateOne {
	pasuo.mutation.Where(ps...)
	return pasuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pasuo *ProfileAndSettingUpdateOne) Select(field string, fields ...string) *ProfileAndSettingUpdateOne {
	pasuo.fields = append([]string{field}, fields...)
	return pasuo
}

// Save executes the query and returns the updated ProfileAndSetting entity.
func (pasuo *ProfileAndSettingUpdateOne) Save(ctx context.Context) (*ProfileAndSetting, error) {
	return withHooks(ctx, pasuo.sqlSave, pasuo.mutation, pasuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pasuo *ProfileAndSettingUpdateOne) SaveX(ctx context.Context) *ProfileAndSetting {
	node, err := pasuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pasuo *ProfileAndSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := pasuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pasuo *ProfileAndSettingUpdateOne) ExecX(ctx context.Context) {
	if err := pasuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (pasuo *ProfileAndSettingUpdateOne) sqlSave(ctx context.Context) (_node *ProfileAndSetting, err error) {
	_spec := sqlgraph.NewUpdateSpec(profileandsetting.Table, profileandsetting.Columns, sqlgraph.NewFieldSpec(profileandsetting.FieldID, field.TypeInt))
	id, ok := pasuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProfileAndSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pasuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, profileandsetting.FieldID)
		for _, f := range fields {
			if !profileandsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != profileandsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pasuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ProfileAndSetting{config: pasuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pasuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{profileandsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pasuo.mutation.done = true
	return _node, nil
}
