// Code generated by ent, DO NOT EDIT.

package ent

import (
	"BazarMessenger/ent/predicate"
	"BazarMessenger/ent/profileandsetting"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ProfileAndSettingDelete is the builder for deleting a ProfileAndSetting entity.
type ProfileAndSettingDelete struct {
	config
	hooks    []Hook
	mutation *ProfileAndSettingMutation
}

// Where appends a list predicates to the ProfileAndSettingDelete builder.
func (pasd *ProfileAndSettingDelete) Where(ps ...predicate.ProfileAndSetting) *ProfileAndSettingDelete {
	pasd.mutation.Where(ps...)
	return pasd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (pasd *ProfileAndSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, pasd.sqlExec, pasd.mutation, pasd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (pasd *ProfileAndSettingDelete) ExecX(ctx context.Context) int {
	n, err := pasd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (pasd *ProfileAndSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(profileandsetting.Table, sqlgraph.NewFieldSpec(profileandsetting.FieldID, field.TypeInt))
	if ps := pasd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, pasd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	pasd.mutation.done = true
	return affected, err
}

// ProfileAndSettingDeleteOne is the builder for deleting a single ProfileAndSetting entity.
type ProfileAndSettingDeleteOne struct {
	pasd *ProfileAndSettingDelete
}

// Where appends a list predicates to the ProfileAndSettingDelete builder.
func (pasdo *ProfileAndSettingDeleteOne) Where(ps ...predicate.ProfileAndSetting) *ProfileAndSettingDeleteOne {
	pasdo.pasd.mutation.Where(ps...)
	return pasdo
}

// Exec executes the deletion query.
func (pasdo *ProfileAndSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := pasdo.pasd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{profileandsetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (pasdo *ProfileAndSettingDeleteOne) ExecX(ctx context.Context) {
	if err := pasdo.Exec(ctx); err != nil {
		panic(err)
	}
}
