// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ProfileAndSetting is the predicate function for profileandsetting builders.
type ProfileAndSetting func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
